### PR TITLE
Support confirmLoading in modalWithForm and refactor code

### PR DESCRIPTION
**Pull request by mumiao**
- Support confirmLoading in modalWithForm
- Enhance modalWithForm codeExamples
- ExampleContainer add otherCode Props

⚠️⚠️⚠️

breaking change:  rename hideModelHandler for hideModalHandler

### CODE REVIEW

**Comment by mumiao** [comment]
link: #222

**Review by liuxy0551 — COMMENTED** [review]
`src/stories/modalWithForm.stories.tsx` 文件下的 hideModelHandler 也需要重命名吧，没有修改到

**Comment by liuxy0551** [comment]
+1

**Comment by liuxy0551** [comment]
方法名的修正同步到 https://dtstack.yuque.com/rd-center/sm6war/oblwbp 吧

**Comment by mumiao** [comment]
> 方法名的修正同步到 https://dtstack.yuque.com/rd-center/sm6war/oblwbp 吧

done

**Pull request merged**
